### ISSUE TITLE
Yaml parsing

### ISSUE THREAD

**Issue by icarob-eng** [icarob-eng/kstability#1]
Gerar models a partir de uma string formatada em yaml.

**Comment by icarob-eng** [comment]
A função de YAML parsing precisa gerar uma `Structure` com nós, barras e cargas, usando múltiplas sintaxes possíveis. Segue exemplo de uma estrutura YAML. Seria útil ter uma função que reverte o processo: de uma estrutura, gera uma String formatada em YAML multilinha.

É necessário achar uma biblioteca de YAML parsing que seja compatível com múltiplas plataformas.  

```yml
---
projeto: nome do projeto # opcional
nos:
   A: [0,0]
   B: [4,0]
   C:
      x: 5
      y: 0

apoios:
   A: # apoio no nó A
      gênero: 1
      direção: vertical
   B:
      gênero: 2
      direção: [0,1]

barras:
   - [A,B]
   - [B,C]

cargas:
   F1:
      nó: A  # único nó = carga pontual
      direção: horizontal
      módulo: 200
   F2:
      nó: [A,C]  # dois nós = carga distribuída
      direção: vertical
      módulo: -20
   F3:
      nó: B
      vetor: [0,-100]
...
```
